spring:
  application.name: chatbot
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
    ollama:
      base-url: http://192.168.0.20:11434
logging.level:
  root: "info"
  org.llucbb.chatbot: "debug"